#!/usr/bin/env bash
# install nginx on your web-01 server
# Nginx should be listening on port 80

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
new_string="\t\tadd_header X-Served-By $(hostname);"
sed -i "s/^\tlocation \/ {$/&\n$new_string/" /etc/nginx/sites-available/default
service nginx restart
